Numpy Array Operation

In [ ]:
import numpy as np


In [2]:
import numpy as np
arr=np.array([[10, 20, 30, 40, 50]])
print("Basic Slicing:",arr[:4])
print("Slicing with step:",arr[0:5:2])
print("Negative Indexing:",arr[-1])

Basic Slicing: [[10 20 30 40 50]]
Slicing with step: [[10 20 30 40 50]]
Negative Indexing: [10 20 30 40 50]


In [29]:
arr_2d=np.array([[1, 2, 3, 10], [4, 5, 6, 20],[7, 8, 9, 30]])
print("Specific element:",arr_2d[1, 2])
print("Entire row:\n",arr_2d[1,:])
print("Entire column:\n",arr_2d[:,1:])
print("Last 2 years sales:",arr_2d[2,2:])

Specific element: 6
Entire row:
 [ 4  5  6 20]
Entire column:
 [[ 2  3 10]
 [ 5  6 20]
 [ 8  9 30]]
Last 2 years sales: [ 9 30]


Sorting

In [ ]:
arr_1d=np.array([3,5,2,9,5,6,1,7])
print("Sorting 1d Array",sorted(arr_1d))
print("Sorting 1d Array",np.sort(arr_1d))
arr_2d=np.array([[2,1],[3,2],[4,3]])
# Axis=0->col axis=1->row
print("Sorting 2d Array:\n",np.sort(arr_2d,axis=0))

Sorting 1d Array [np.int64(1), np.int64(2), np.int64(3), np.int64(5), np.int64(5), np.int64(6), np.int64(7), np.int64(9)]
Sorting 1d Array [1 2 3 5 5 6 7 9]
Sorting 2d Array:
 [[2 1]
 [3 2]
 [4 3]]


#Filter

In [39]:
number=np.array([3,5,2,9,5,6,1,7])
even_number=number[number%2==0]
print("Even numbers:",even_number)

Even numbers: [2 6]


##Filter with mask

In [40]:
marks=np.array([67,34,10,23,50,97,54])
mask_pass=marks>35
print("More than 35(mask):",mask_pass)

More than 35(mask): [ True False False False  True  True  True]


Index

In [41]:
sales=np.array([25000,12000,65000,80000])
idc=[1,3]
res=sales[idc]
print(res)

[12000 80000]
