numpy array and basics

In [1]:
import numpy as np

###Array creation

In [2]:
# 1d Array cretion
arr_1d = np.array([10, 20, 30, 40])
print(arr_1d),type(arr_1d)

[10 20 30 40]


(None, numpy.ndarray)

In [8]:
arr_2d=np.array([[10, 20, 30,], [40, 50, 60],[70, 80, 90]])
print(arr_2d)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [10]:
#ap1
cost_list=[10, 20, 30, 40]
print("selling list",cost_list*2)
cost_arr=np.array([10, 20, 30, 40])
print("selling list",cost_arr*2)
#ap2
d1_list=[10, 20, 30, 40]
d2_list=[20,15,45,50]
print("total sales",d1_list+d2_list)
d1_arr=np.array([10, 20, 30, 40])
d2_arr=np.array([20, 15, 45, 50])
print("total sales",d1_arr+d2_arr)

selling list [10, 20, 30, 40, 10, 20, 30, 40]
selling list [20 40 60 80]
total sales [10, 20, 30, 40, 20, 15, 45, 50]
total sales [30 35 75 90]


In [1]:
print("Rohan")

Rohan
