numpy array and basics

In [1]:
import numpy as np

###Array creation

In [2]:
# 1d Array cretion
arr_1d = np.array([10, 20, 30, 40])
print(arr_1d),type(arr_1d)

[10 20 30 40]


(None, numpy.ndarray)

In [8]:
arr_2d=np.array([[10, 20, 30,], [40, 50, 60],[70, 80, 90]])
print(arr_2d)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [10]:
#ap1
cost_list=[10, 20, 30, 40]
print("selling list",cost_list*2)
cost_arr=np.array([10, 20, 30, 40])
print("selling list",cost_arr*2)
#ap2
d1_list=[10, 20, 30, 40]
d2_list=[20,15,45,50]
print("total sales",d1_list+d2_list)
d1_arr=np.array([10, 20, 30, 40])
d2_arr=np.array([20, 15, 45, 50])
print("total sales",d1_arr+d2_arr)

selling list [10, 20, 30, 40, 10, 20, 30, 40]
selling list [20 40 60 80]
total sales [10, 20, 30, 40, 20, 15, 45, 50]
total sales [30 35 75 90]


In [1]:
print("Rohan")

Rohan


In [6]:
import time as t
import numpy as np
#list
start=t.time()
list_time=[i*2 for i in range(1000000)]
end=t.time()
print("list time",end-start)
#numpy array
start=t.time()
arr_time = np.arange(1000000)*2
end=t.time()
print("array operation:" \
"",end-start)

list time 0.08425617218017578
array operation: 0.004196643829345703


creating array from scratch

In [11]:
#Zeroes
zeros = np.zeros((3, 4))
print("Zeroes:\n", zeros)
#ones
ones = np.ones((3, 2))
print("Ones:\n", ones)
#full
full = np.full((3, 3), 7)
print("Full:\n", full)
#random
random = np.random.random((3, 3))
print("Random matrix(0 to 1):\n", random)
#sequence start,stop,step
sequence = np.arange(10,31)
print("Sequence of 10 to 30:\n", sequence)

Zeroes:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Full:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Random matrix(0 to 1):
 [[0.00140915 0.43297581 0.64658172]
 [0.02556106 0.06919514 0.73455088]
 [0.59543378 0.76098398 0.08581081]]
Sequence of 10 to 30:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


Vector,matrix and Tensor

In [3]:
import numpy as np
vector=np.array([10, 20, 30, 40])
print("Vector:\n", vector)
matrix=np.array([[10, 20, 30], [40, 50, 60]])
print("Matrix:\n", matrix)
tensor=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("Tensor:\n", tensor)

Vector:
 [10 20 30 40]
Matrix:
 [[10 20 30]
 [40 50 60]]
Tensor:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Array properties

In [3]:
import numpy as np
arr=np.array([[10, 20, 30], [40, 50, 60]])
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Size:", arr.size)
print("Data type:", arr.dtype)

Shape: (2, 3)
Dimensions: 2
Size: 6
Data type: int64


Array reshaping

In [ ]:
import numpy as np
arr=np.arange(12)
print("Array:", arr)
reshape=arr.reshape((3,4))
print("Reshape:\n", reshape)
mat=np.array([[10, 20, 30], [40,hr50, 60]])
f1=mat.flatten()
print(f1)


Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshape:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[10 20 30 40 50 60]
